/* Single source of truth for the homepage journey rows and legacy service pages. */
export function getServices(t) {
  return [
    {
      slug: 'diagnostic-map',
      to: '/audit',
      num: '01',
      kicker: t('Stage one', 'المرحلة الأولى'),
      title: t('Diagnostic Map', 'خريطة التشخيص'),
      short: t('We identify your industry demand, competitors, funnel leaks, response gaps and fastest route to booked appointments.', 'نحدد طلب القطاع والمنافسين وتسريبات القمع وفجوات الاستجابة وأسرع طريق للمواعيد المحجوزة.'),
      lede: t('A diagnostic map shows where demand exists, where your website loses it, where follow-up breaks, and what to build first.', 'خريطة التشخيص توضح أين يوجد الطلب وأين يضيع داخل الموقع والمتابعة وما يجب بناؤه أولاً.'),
      points: [t('Competitor visibility snapshot', 'لقطة حضور المنافسين'), t('Current funnel and CRM review', 'مراجعة القمع ونظام CRM'), t('Industry-specific 90-day roadmap', 'خارطة ٩٠ يوماً حسب القطاع')],
      metric: '90d',
      metricLabel: t('Build plan', 'خطة البناء'),
    },
    {
      slug: 'demand-capture',
      to: '/services/seo-uae',
      num: '02',
      kicker: t('Stage two', 'المرحلة الثانية'),
      title: t('Demand Capture', 'التقاط الطلب'),
      short: t('SEO, Google and paid social aimed at the exact searches and comparisons your UAE buyers make.', 'تحسين بحث وجوجل وإعلانات اجتماعية تستهدف بحث ومقارنات المشترين في الإمارات.'),
      lede: t('Demand capture puts your business in front of high-intent buyers before they choose a competitor.', 'التقاط الطلب يضع نشاطك أمام المشترين ذوي النية العالية قبل اختيار منافس.'),
      points: [t('Commercial keyword map', 'خريطة كلمات تجارية'), t('Paid acquisition structure', 'هيكلة اكتساب مدفوع'), t('Industry landing routes', 'مسارات هبوط حسب القطاع')],
      metric: 'Intent',
      metricLabel: t('First filter', 'الفلتر الأول'),
    },
    {
      slug: 'conversion-path',
      to: '/landing-pages-dubai',
      num: '03',
      kicker: t('Stage three', 'المرحلة الثالثة'),
      title: t('Conversion Path', 'مسار التحويل'),
      short: t('Offer-specific landing pages and forms that turn traffic into calls, WhatsApp enquiries and booked appointments.', 'صفحات ونماذج حسب العرض تحول الزيارات إلى مكالمات وواتساب ومواعيد محجوزة.'),
      lede: t('Conversion paths keep the prospect moving from problem to proof to enquiry without sending them into a generic website maze.', 'مسارات التحويل تنقل العميل من المشكلة إلى الإثبات ثم الاستفسار دون ضياع داخل موقع عام.'),
      points: [t('Offer-specific pages', 'صفحات حسب العرض'), t('Fast mobile layouts', 'تخطيطات جوال سريعة'), t('Qualification forms', 'نماذج تأهيل')],
      metric: 'Booked',
      metricLabel: t('Core outcome', 'النتيجة الأساسية'),
    },
    {
      slug: 'follow-up-system',
      to: '/services/crm-funnels',
      num: '04',
      kicker: t('Stage four', 'المرحلة الرابعة'),
      title: t('Follow-Up System', 'نظام المتابعة'),
      short: t('CRM, WhatsApp automation, lead routing and reminders so no enquiry depends on someone remembering.', 'CRM وأتمتة واتساب وتوجيه العملاء والتذكير حتى لا يعتمد أي استفسار على الذاكرة.'),
      lede: t('Follow-up systems protect speed-to-lead, show rate and sales accountability after the form is submitted.', 'أنظمة المتابعة تحمي سرعة الاستجابة ومعدل الحضور ومساءلة المبيعات بعد إرسال النموذج.'),
      points: [t('Lead routing and stages', 'توجيه ومراحل العملاء'), t('WhatsApp sequences', 'تسلسلات واتساب'), t('Attribution reporting', 'تقارير النسب')],
      metric: 'SLA',
      metricLabel: t('Response rhythm', 'إيقاع الاستجابة'),
    },
  ]
}
