/* Single source of truth for per-route SEO metadata.
   Used by build-sitemap.mjs and build-prerender.mjs.
   Page components also import this via src/seo-routes.js so titles/descriptions never drift. */

export const SITE = 'https://ignite-scale.com'

export const ROUTES = [
  {
    path: '/',
    title: 'Ignite Scale | Dubai Paid Social, Web & Lead Funnels',
    description: "Dubai growth agency engineering paid social, content and funnels for luxury real estate, cosmetic clinics and B2B brands. Targeting 2–5× ROAS. Book a free strategy call.",
    changefreq: 'weekly', priority: 1.0,
    breadcrumbs: [{ name: 'Home', url: '/' }],
  },
  {
    path: '/services',
    title: 'Digital Marketing Services Dubai | Ignite Scale',
    description: 'Paid social on Meta, TikTok and Google, conversion websites, lead generation and creative production for Dubai brands. Book a free consultation.',
    changefreq: 'monthly', priority: 0.9,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }],
  },
  {
    path: '/services/paid-social',
    title: 'Paid Social Agency Dubai | Meta, TikTok & Google',
    description: 'Paid social advertising in Dubai across Meta, TikTok, Snapchat and Google. Targeting 2–5× ROAS and meaningful CPL reduction. Free campaign audit.',
    changefreq: 'monthly', priority: 0.85,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }, { name: 'Paid Social', url: '/services/paid-social' }],
  },
  {
    path: '/services/creative',
    title: 'UGC Video & Creative Ads Dubai | Ignite Scale',
    description: 'UGC video, ad creative and copywriting for Dubai brands. In-house production, 48-hour turnaround, conversion-focused. Typical 3–5× engagement lift.',
    changefreq: 'monthly', priority: 0.85,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }, { name: 'Content & Creative', url: '/services/creative' }],
  },
  {
    path: '/services/funnels',
    title: 'Landing Pages & Lead Funnels Dubai | Ignite Scale',
    description: 'Conversion-optimised landing pages and lead funnels for Dubai brands. Real estate, cosmetics, hospitality. CRO built in. Free funnel audit.',
    changefreq: 'monthly', priority: 0.85,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Services', url: '/services' }, { name: 'Funnels', url: '/services/funnels' }],
  },
  {
    path: '/dubai-marketing-agency',
    title: 'Best Marketing Agency in Dubai | Ignite Scale',
    description: 'Looking for a Dubai marketing agency? Ignite Scale builds paid social, websites and lead funnels for ambitious UAE brands. Book a free strategy session.',
    changefreq: 'monthly', priority: 0.9,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Dubai Marketing Agency', url: '/dubai-marketing-agency' }],
  },
  {
    path: '/meta-ads-dubai',
    title: 'Meta Ads Agency Dubai | Facebook & Instagram Experts',
    description: 'Meta Ads management in Dubai. We run Facebook and Instagram campaigns targeting 2–5× ROAS for real estate, cosmetics and B2B. Free ad audit.',
    changefreq: 'monthly', priority: 0.85,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Meta Ads Dubai', url: '/meta-ads-dubai' }],
  },
  {
    path: '/tiktok-ads-dubai',
    title: 'TikTok Ads Agency Dubai | Ignite Scale',
    description: 'TikTok advertising in Dubai. High-performing campaigns targeting Gen Z and millennial audiences with lower CPMs than Meta. Free audit available.',
    changefreq: 'monthly', priority: 0.85,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'TikTok Ads Dubai', url: '/tiktok-ads-dubai' }],
  },
  {
    path: '/web-design-dubai',
    title: 'Web Design Dubai | Conversion-Optimised Websites',
    description: 'Professional website design in Dubai. Conversion-optimised landing pages for real estate, cosmetics, hospitality and B2B. Mobile-first, fast-loading, SEO-ready.',
    changefreq: 'monthly', priority: 0.85,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Web Design Dubai', url: '/web-design-dubai' }],
  },
  {
    path: '/results',
    title: 'Client Results & Case Studies | Ignite Scale Dubai',
    description: 'Real results from Dubai brands: +247% qualified leads in 90 days, 4.2× lower cost per reservation, 61% CPL reduction in luxury auto. No vanity metrics.',
    changefreq: 'monthly', priority: 0.8,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Results', url: '/results' }],
  },
  {
    path: '/process',
    title: 'Our Growth Process for Dubai Brands | Ignite Scale',
    description: 'Our 4-step growth process: strategy discovery, content and campaign build, launch and optimise, then scale. Transparent and data-driven.',
    changefreq: 'monthly', priority: 0.7,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Process', url: '/process' }],
  },
  {
    path: '/book',
    title: 'Book a Free Strategy Call | Ignite Scale Dubai',
    description: 'Book a free 45-minute strategy call with Ignite Scale. We audit your social presence, analyse competitors, and build a 90-day growth roadmap. No obligation.',
    changefreq: 'monthly', priority: 0.9,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Book', url: '/book' }],
  },
  {
    path: '/faq',
    title: 'Social Media Marketing FAQ | Ignite Scale Dubai',
    description: 'Answers to the most common questions Dubai businesses ask before working with Ignite Scale: timelines, platforms, budgets, content creation, Arabic content, ROI.',
    changefreq: 'monthly', priority: 0.6,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'FAQ', url: '/faq' }],
  },
  {
    path: '/blog/meta-ads-mistakes',
    title: '5 Meta Ads Mistakes Costing You Money | Dubai Guide',
    description: 'The 5 biggest Meta Ads mistakes Dubai businesses make, with actionable fixes that typically lift ROAS 50–100%.',
    changefreq: 'monthly', priority: 0.7,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: '5 Meta Ads Mistakes', url: '/blog/meta-ads-mistakes' }],
    article: { datePublished: '2026-03-20', headline: '5 Meta Ads Mistakes Costing You Money' },
  },
  {
    path: '/blog/tiktok-vs-instagram-ads',
    title: 'TikTok vs Instagram Ads 2026 | Dubai Comparison',
    description: 'TikTok vs Instagram Ads 2026: cost, audience demographics, conversion rates and best industries for each. When to use which platform in Dubai.',
    changefreq: 'monthly', priority: 0.7,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'TikTok vs Instagram', url: '/blog/tiktok-vs-instagram-ads' }],
    article: { datePublished: '2026-05-04', headline: 'TikTok vs Instagram Ads 2026: Which Platform to Choose for Dubai' },
  },
  {
    path: '/blog/reduce-cost-per-lead',
    title: 'How to Cut Ad Cost Per Lead by 60% | Ignite Scale',
    description: 'Step-by-step framework for reducing CPL 60–80%: landing page optimisation, audience targeting, funnel design, copywriting. Tested on 50+ Dubai campaigns.',
    changefreq: 'monthly', priority: 0.7,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Blog', url: '/blog' }, { name: 'Cut CPL by 60%', url: '/blog/reduce-cost-per-lead' }],
    article: { datePublished: '2026-04-12', headline: 'How to Cut Your Ad Cost Per Lead by 60%' },
  },
  {
    path: '/case-study/dubai-real-estate-4-8x-roas',
    title: 'Real Estate: 4.8× ROAS in 90 Days | Case Study',
    description: "How we lifted a Dubai property developer's ROAS from 1.2× to 4.8× in 90 days, with CPL down 68%. Complete strategy breakdown.",
    changefreq: 'yearly', priority: 0.75,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Case Studies', url: '/results' }, { name: 'Real Estate', url: '/case-study/dubai-real-estate-4-8x-roas' }],
    article: { datePublished: '2026-01-28', headline: 'Real Estate Case Study: 4.8× ROAS in 90 Days' },
  },
  {
    path: '/case-study/dubai-cosmetics-320-leads',
    title: 'Cosmetic Clinic: 320 Leads in 60 Days | Case Study',
    description: 'How a Dubai cosmetic clinic went from 0 to 320 qualified leads in 60 days. Lead generation strategy, conversion optimisation, ads management.',
    changefreq: 'yearly', priority: 0.75,
    breadcrumbs: [{ name: 'Home', url: '/' }, { name: 'Case Studies', url: '/results' }, { name: 'Cosmetics', url: '/case-study/dubai-cosmetics-320-leads' }],
    article: { datePublished: '2026-02-15', headline: 'Cosmetic Clinic Case Study: 320 Qualified Leads in 60 Days' },
  },
]
